### ISSUE TITLE
Question: Would you consider making a readVTK package?

### ISSUE THREAD

**Issue by AhmedSalih3d** [jipolanco/WriteVTK.jl#74] opened 2020-08-29 10:45 UTC
From my perspective this is one of the best packages I have seen w.r.t. working with VTK in any language. I was therefore curious if you think readVTK would ever be possible, but maybe there is a hurdle (other than time constraints) which I do not know about?

Kind regards

**Comment by jipolanco** [comment] 2020-08-29 16:52
Hi, I appreciate your words and I'm glad you find this package useful!

This was discussed some time ago in #23. I think yes, it should be possible to read VTK files, although reading all possible kinds of VTK files (including e.g. those generated by the official VTK libraries) may be a bit challenging. 

More realistically, it shouldn't be too hard to add functionality for reading files generated by WriteVTK, and I agree that this would be really useful and a good thing to have. To be honest though, I currently lack the motivation for doing so, as I personally don't need this for my work, and I've been busy with other projects. But I'd be very happy to guide with the implementation of VTK reading functionality, either within WriteVTK or as a separate package.

I'm closing this as it's a duplicate of #23.

**Closed by jipolanco** 2020-08-29 16:52 UTC
